# Site Settings
title: Peru Iparragirre
email: iparragirre.peru@yahoo.es
description: >
  
baseurl: "/honi-buruz"
url: "nomadagaldua.github.io"
twitter_username: 
github_username:  
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
